export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_POINTS = 'CART_SAVE_POINTS';
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT';